apiVersion: v1
kind: Service
metadata:
  name: api-srv
spec:
  type: ClusterIP
  selector:
    component: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: 501107650877.dkr.ecr.eu-central-1.amazonaws.com/msb-hub
          ports:
            - containerPort: 3000
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-srv
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              value: pgspassword
            - name: DATABASE_URL
              value: fakedb
