pipeline {

    agent any

    tools {nodejs "nodejs"}

    environment {
        CI = 'true'
    }
    
    stages {
        stage('grant permission'){
            steps{
                sh "chmod +x -R ${env.WORKSPACE}"
            }
        }

        stage('Install dependencies') {
            steps {
                sh 'cd api && npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo finish'
            }
        }
    }
}