pipeline {

    agent any

    tools {nodejs "nodejs"}

    environment {
        CI = 'true'
    }
    stages {
        stage('Install dependencies') {
            steps {
                sh 'cd api && npm install'
                sh "chmod +x -R ${env.WORKSPACE}"
                sh './jenkins/scripts/test.sh'
            }
        }

        stage('Deliver') {
            steps {
                sh 'echo finish'
            }
        }
    }
}