pipeline {

    agent any

    tools {nodejs "nodejs"}

    environment {
        CI = 'true'
    }
    
    stages {
        stage('grant permission'){
            steps {
                sh "chmod +x -R ${env.WORKSPACE}"
            }
        }

        stage('Install dependencies') {
            steps {
                sh 'cd api && npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }

        stage('docker build image') {
            steps {
                sh 'cd api && docker build -t msb-hub-api -f Dockerfile.prod .'
            }
        }
        
        stage('push to ecr') {
            steps {
                sh 'aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 501107650877.dkr.ecr.eu-central-1.amazonaws.com'
                sh 'docker tag msb-hub-api:latest 501107650877.dkr.ecr.eu-central-1.amazonaws.com/msb-hub:latest'
                sh 'docker push 501107650877.dkr.ecr.eu-central-1.amazonaws.com/msb-hub:latest'
            }
        }

        stage('k8s deploy') {
            steps {
                withKubeConfig(caCertificate: '', clusterName: '', contextName: '', credentialsId: 'K8S', namespace: '', serverUrl: '') {
                    sh 'curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.22.6/2022-03-09/bin/linux/amd64/kubectl'
                    sh 'curl -o kubectl.sha256 https://s3.us-west-2.amazonaws.com/amazon-eks/1.22.6/2022-03-09/bin/linux/amd64/kubectl.sha256'
                    sh 'chmod +x ./kubectl'
                    sh 'mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin'
                    sh "echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc"
                    sh 'kubectl get  pods'
            }
        }
    }
  }
}