apiVersion: v1
kind: Service
metadata:
  name: api-srv
spec:
  type: ClusterIP
  selector:
    component: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: gsdatabase/api:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: pg-configmap
          resources:
            limits:
              memory: 500Mi
              cpu: 500m
            requests:
              memory: 350Mi
              cpu: 200m
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
