name: api-workflow
on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/api.yml"
    branches: [main]
  pull_request:
    branches: [main]
defaults:
  run:
    shell: bash
    working-directory: api/
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Set up node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
