name: CI
on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: thedoorknobster
  REPO: thedoorknobster/sample-app

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all commits
          fetch-depth: 0

      - name: Semantic versioning
        id: versioning
        uses: LongOddCode/semantic-versioning-tag@0.6.0

      - name: validation and set params
        run: |
          echo ${{ steps.versioning.outputs.major }}
          echo ${{ steps.versioning.outputs.minor }}
          echo ${{ steps.versioning.outputs.patch }}
          echo ${{ steps.versioning.outputs.prerelease }}
          echo ${{ steps.versioning.outputs.buildmetadata }}

      - name: Create Release
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: ${{ steps.versioning.outputs.version }}
          prerelease: false
